[phases.setup]
aptPkgs = ["libgl1", "libglib2.0-0", "libxcb1", "libxrender1", "libxext6", "libsm6"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "pip uninstall -y opencv-python opencv-contrib-python || true",
    "pip install --force-reinstall --no-deps opencv-python-headless==4.10.0.84"
]

[start]
cmd = "python main.py"

[variables]
NIXPACKS_PYTHON_VERSION = "3.12"
RAILPACK_PYTHON_VERSION = "3.12"
